deploy1: 
  argocd:
    syncwave:
      deployment: 5
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'quay.io/nadavnoach/hello_world'
      tag: 'chart_v1'

  service:
      servicePort: 8080

deploy2: 
  argocd:
    syncwave:
      deployment: 10
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/nadavnoach/hello_world'
    tag: 'chart_v1'

  service:
    servicePort: 8080